version: "3.3"
services:
    server-nginx:
        image: "nginx:latest"
        volumes:
            - ./server/api/:/usr/sites/starit_server/
            - ./config/nginx/server.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8181:80"
        environment:
            - NGINX_PORT=80
        links:
            - server-php-api
        container_name: "server_nginx"
        working_dir: /usr/sites/starit_server
    server-php-api:
        volumes:
            - ./server/api/:/usr/sites/starit_server/
        links:
            - server-mysql
        container_name: "server_php"
        build:
            context: .
            dockerfile: ./config/docker/DockerServer
        working_dir: /usr/sites/starit_server
    server-mysql:
        image: "mysql:5.7.32"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=starit_server
        ports:
            - "33306:3306"
        container_name: "server_mysql"
    
    app-nginx:
        image: "nginx:latest"
        volumes:
            - ./server/backend/:/usr/sites/starit_app/
            - ./config/nginx/app.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        environment:
            - NGINX_PORT=80
        links:
            - app-php
        container_name: "app_nginx"
        working_dir: /usr/sites/starit_app/
    app-php:
        volumes:
            - ./server/backend/:/usr/sites/starit_app/
        links:
            - app-backend-mysql
        container_name: "app_backend"
        build:
            context: .
            dockerfile: ./config/docker/DockerApp
        working_dir: /usr/sites/starit_app
    app-backend-mysql: 
        image: "mysql:5.7.32"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=starit_app
        ports:
            - "33307:3306"
        container_name: "app_backend_mysql"

    app-node-customer:
        build:
            context: ./
            dockerfile: ./config/docker/DockerNode
            args:
                - service_path=customer
                - port=3000
        ports: 
            - 3000:3000
        container_name: "app_node_customer"
        stdin_open: "true"
        volumes:
            - ./customer/:/usr/sites/starit_app/
            - /usr/sites/starit_app/customer/node_modules
    
    # app-node-business:
    #     build:
    #         context: ./
    #         dockerfile: /config/docker/DockerNode
    #         args:
    #             - service_path=business
    #             - port=3001
    #     ports: 
    #         - "3001:3000"
    #     container_name: "app_node_business"
    #     stdin_open: "true"
    #     volumes:
    #         - ./business/:/usr/sites/starit_app/
    #         - /usr/sites/starit_app/node_modules
    landing-node-customer:
        build:
            context: ./
            dockerfile: ./config/docker/DockerNode
            args:
                - service_path=landing/customer-landing
                - port=3002
        ports: 
            - "3002:3000"
        container_name: "landing_node_customer"
        stdin_open: "true"
        volumes:
            - ./landing/customer-landing/:/usr/sites/starit_app/
            - /usr/sites/starit_app/node_modules

    landing-node-business:
        build:
            context: ./
            dockerfile: ./config/docker/DockerNode
            args:
                - service_path=landing/business-landing
                - port=3003
        ports: 
            - "3003:3000"
        container_name: "landing_node_business"
        stdin_open: "true"
        volumes:
            - ./landing/business-landing/:/usr/sites/starit_app/
            - /usr/sites/starit_app/node_modules